### ISSUE TITLE
[NSML] pre-trained model / 깃헙 모델 사용 관련

### ISSUE THREAD

**Issue by sohyunwriter** [hunminjeongeum-korean-competition-2021/conversation-summary#1]
# 주제
- pre-trained model / 깃헙 모델 사용 관련

# 상황 (자세히 작성해주시면 좋습니다.)
- 대회 규정 질문드립니다

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 대화요약에서 pre-trained model 사용 불가능하다고 알고 있습니다. 그렇다면 다음의 가능 여부가 궁금합니다.
- 1) 깃헙에 오픈소스로 공개된 코드에 착안해 저희 데이터셋에 맞게 customized하는 것이 가능한지?
- 2) 기존에 있는 모델 구조를 weight만 지우면 해당 알고리즘은 사용할 수 있는건지?

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요.
말씀하신 2가지 사항 모두 활용 가능합니다.
감사합니다.

**Comment by dan-legit** [comment]
추가 질문: Tokenizer도 마찬가지로 pre-trained를 사용하진 않되, 공개된 코드를 사용하여 주어진 데이터로 scratch 부터 학습하여 사용해야 하는 것이죠?

**Comment by vetaerang** [comment]
답변 정정드립니다.
pre-trained tokenizer 사용 가능합니다. (기존에 사용 불가하다고 답변 드렸었습니다.)
혼동 드려 죄송합니다.

**Comment by dan-rtzr** [comment]
@taerangi 그렇다면 외부 공개된 데이터로 직접 tokenizer를 학습시켜서 사용해도 되나요?

**Comment by vetaerang** [comment]
@dan-rtzr 네 가능합니다.
