### ISSUE TITLE
[Dataset] evaluation 스크립트 제공 요청

### ISSUE THREAD

**Issue by codertimo** [hunminjeongeum-korean-competition-2021/conversation-summary#10]
# 주제
- ROUGE metric 측정을 위해서 사용되는 evaluation script 요청

# 상황 (자세히 작성해주시면 좋습니다.)
- 주최측에서는 ROUGE 기반 metric 을 사용하여 모델의 성능을 평가한다고 고지하였습니다.
- 한국어의 경우에는 주로 어절단위가 아닌 형태소 단위로 ROUGE 를 계산하는 것으로 알려져 있습니다.
- 이전 문서요약 역량평가에서도 형태로 단위의 ROUGE 를 사용한다고 Q&A에서 답변주셨습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- Q1. 본 대회에서는 ROUGE 를 계산할 때 형태소 단위를 사용하는지 질의드립니다. 
- Q2. Q1이 맞다고 한다면, 어떤 형태소 분석기를 사용하는지 알려주시면 감사하겠습니다.
- 각 참가자 간의 착오가 없도록 코드 형태로 평가 스크립트 예시를 공유해 주시면 감사하겠습니다.

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요.
본 대회에서도 역량평가와 마찬가지로 형태소 단위를 사용합니다.
평가 스크립트는 말씀하는 것처럼 코드 형태로 공유해 드리겠습니다.
감사합니다.

**Comment by Usurper47** [comment]
평가 스크립트 어디서 확인할 수 있을까요?
