### ISSUE TITLE
[NSML] 세션 종료 불가능 오류

### ISSUE THREAD

**Issue by cosmoquester** [hunminjeongeum-korean-competition-2021/conversation-summary#11]
# 주제
- NSML에서 세션을 끄고 싶어도 꺼지지 않는 상황이 발생하는데 이럴 때 어떻게 해야하나요?

# 상황 (자세히 작성해주시면 좋습니다.)

- 베이스라인 코드를 돌리거나 테스트용으로 코드를 돌려보는데 이유는 알 수 없이 아래와 같은 에러가 발생하는데(현재 두 번째 발생함), 세션 로그에는 아래와 같은 Allocating! 이라는 글자만 계속 찍히고 정지하기 위해 Stop을 눌러도 ` Failed to change the session status.`라고 나오면서 정지가 되지 않습니다. nsml 웹에서도 안되고 nsml stop 커맨드도 안되네요. 세션 한 개 밖에 띄우지도 못하는데 이러면 수행에 차질이 있을 것 같습니다.

```
Allocating !
Allocating !
Allocating !
Allocating !
Allocating !
Allocating !
Allocating !
Allocating !
Allocating !
```

```sh
$ nsml stop nia2040/dialogue/7
Stopping nia2040/dialogue/7 is failed
Error: Session error: 'Failed to stop session [nia2040/dialogue/7]'
FATA[2021/10/10 15:43:33.227] Internal server error
```

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)

돌려봤던 샘플

```python
# nsml: dacon/nia-pytorch:1.0
import os

import nsml

if __name__ == "__main__":
    print("NSML test")

    def save(name):
        os.makedirs(name, exist_ok=True)
        with open(os.path.join(name, "hello.txt"), "w") as f:
            f.write("HELLO")

    def load(name):
        with open(name) as f:
            text = f.read()
            print("Loaded:", text)
        return text

    nsml.bind(save=save, load=load)

    for i in range(10):
        nsml.save(str(i))
```

# 기타 문의 사항
-

**Comment by ZIZUN** [comment]
세션끄는건 nsml rm nia2040/dialogue/7 하심돼요.. 서버가 불안정한거같아요 ㅠ

**Comment by cosmoquester** [comment]
> 세션끄는건 nsml rm nia2040/dialogue/7 하심돼요.. 서버가 불안정한거같아요 ㅠ

아하 명령어로 rm 하는 건 되네요 감사합니다. 근데 진짜 서버가 거의 10번 run해야 1번실행되네요...
