### ISSUE TITLE
[NSML] GPU 부족현상

### ISSUE THREAD

**Issue by jonhyuk0922** [hunminjeongeum-korean-competition-2021/conversation-summary#12]
# 주제
- GPU 부족현상

# 상황 (자세히 작성해주시면 좋습니다.)
- 팀당 1개의 GPU라고 하셨는데, 60개팀보다 많은 208개 GPU가 할당되었음에도 저희팀은 1개도 돌리지 않았는데 강요 가능한 GPU가 없습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 아래와 같은 상황입니다. 해결을 위해 팀당 GPU갯수 제한을 걸어주셔야 모든 팀들이 사용할 수 있을 것 같습니다.
![스크린샷 2021-10-10 오후 5 17 01](https://user-images.githubusercontent.com/76195885/136688098-72ab940d-4321-4a8c-9049-d8728f4bd7c9.png)

# 기타 문의 사항
-

**Comment by KHY13** [comment]
저희팀도 같은 상황입니다.

**Comment by ZIZUN** [comment]
저도요 빨리 하고싶어요

**Comment by fd873630** [comment]
저희 팀은 음성인식 분야에 참여하고 있는 inha_ASR 팀인데 음성인식 분야도 같은 상황입니다. 예선전 시간이 짧은 만큼 빠른 피드백 부탁드립니다

**Comment by MattYoon** [comment]
이슈 올라온지 4시간 지났는데도 같은 상황이네요

**Comment by bluebrush** [comment]
@jonhyuk0922 님, 조치되었습니다.  이상있으시면 다시 올려주세요.

**Comment by bluebrush** [comment]
@MattYoon 님, 이슈가 지속되나요?
nsml run 실행 명령줄을 포함한 전체 오류 메시지가 확인될 수 있도록 붙여넣어주세요.

**Comment by bluebrush** [comment]
@fd873630 님,  
`nia1019/stt_1/79  Not created yet          Allocated                            0              62.22 KB  normal`
위 상태로 자원이 할당되어 있음이 확인됩니다. 
Alocated 상태는 docker image build, image pull, 내부 모듈 설치 등으로 시간이 길게 소요될 수 있습니다. 
혹시, 취소시 남은 있는 세션이 있다면, 
nsml rm -f [session-id] 로 삭제할 수 있습니다. 
정상적으로 삭제/종료되면, 1-2분 정도 후에 자원이 회수되어 재사용 가능합니다. 
docker image의 경우, 동일 이미지인 경우 cache되어 최초 실행시보다 상대적으로 빠르게 생성됩니다. 
docker image와 다르게 setup.py와 requirements.txt에 설치용도로 저정된 모듈은 세션 실행시 항상 설치하게 되므로 참고부탁드립니다. 
이후, 오류 문의시 nsml run 명령줄을 포함한 CLI 메시저 전체를 포함하면 분석이 더 용이하므로 참고부탁드립니다. 
추가 문의는 새로운 이슈 생성으로 부탁드립니다. 현재 댓글의 문의 내용의 원이 모두 달라서 개별적인 답변이 나갈 수 있기때문입니다.

**Comment by bluebrush** [comment]
@KHY13 님, nsml run 명령줄을 포함한 오류 메시지를 붙여주시기 바랍니다. (추가 문의시 새로운 이슈 생성을 부탁드립니다. )
참고로, 
새로운 GPU 노드에서는 nsml run에서 새로운 docker image를 사용할 경우, image build 시간으로 인한 느린 상황이 있을 수 있습니다. 현재 최대 5개의 서로 다른 노드에 할당 될 수 있으며, 동일한 docke image에 대해서 5번을 build 과정이 발생할 수 있습니다. 
session 삭제 명령은 `nsml rm -f [session-id]`이며, 종료과정에 문제가 되는 세션이 있으시면 참고부탁드립니다.

**Comment by bluebrush** [comment]
@ZIZUN 님, 오류 상황이 지속되고 있다면, 
nsml run 명령줄을 포함한 오류 메시지를 붙여주시기 바랍니다. (추가 문의시 새로운 이슈 생성을 부탁드립니다. )
참고로,
새로운 GPU 노드에서는 nsml run에서 새로운 docker image를 사용할 경우, image build 시간으로 인한 느린 상황이 있을 수 있습니다. 현재 최대 5개의 서로 다른 노드에 할당 될 수 있으며, 동일한 docke image에 대해서 5번을 build 과정이 발생할 수 있습니다.
session 삭제 명령은 nsml rm -f [session-id]이며, 종료과정에 문제가 되는 세션이 있으시면 참고부탁드립니다.

**Comment by MattYoon** [comment]
@bluebrush 지금은 잘되네요. 일시적인 문제였나 봅니다. 감사합니다.
