### ISSUE TITLE
[NSML]gpu status 보는법

### ISSUE THREAD

**Issue by ZIZUN** [hunminjeongeum-korean-competition-2021/conversation-summary#13]
# 주제
- gpu status 보는법

# 상황 (자세히 작성해주시면 좋습니다.)
- 혹시 gpu 사용량이나 상태를 보는 방법이 있을까요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
-  nsml status -r 하면 자원현황을 볼 수 있다고 하셨는데, 명령어가 관리자만 쓸수있는것인지 저는 안되네요.
- 혹시 nvidia-smi처럼 자원현황 볼수있는 법 있으면 알려주시면 감사하겠습니다! 
- 참고로 웹 status는 gpu를 사용하여도 현황이 나타나질 않네요!
![image](https://user-images.githubusercontent.com/24732802/136721507-284740f9-f183-4c90-bd88-80801e940e1b.png)

# 기타 문의 사항
-

**Comment by Usurper47** [comment]
저도 안됩니다!
