### ISSUE TITLE
[Dataset] 데이터셋 다운로드 가능 여부

### ISSUE THREAD

**Issue by cosmoquester** [hunminjeongeum-korean-competition-2021/conversation-summary#15]
# 주제
- Training/Test 데이터셋이 NSML을 통해 제공되고 있는데 이 데이터들을 다운로드 받아서 분석하거나 전처리하는 등의 행위는 금지인가요?

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)

- 현재 데이터셋이 NSML로 제공되고 있고 데이터셋을 다운받는 기능를 플랫폼에서 직접적으로 제공하지는 않는 것 같습니다. 그런데 또 NSML이 기술적으로는 데이터셋을 다운받는 것이 불가능하지 않은 시스템인 거 같습니다. 또한 NSML에서 데이터셋을 다운받는 것의 허용여부에 대해 규정 상 직접적으로 언급된 것은 없고 비슷하게 운영규정에 불공정 행위로 "정상적인 대회 진행방법 외에 문제 데이터셋을 전자적 물리적으로 확보하여 도전문제를 해결하였거나, 시도한 경우", "비정상적인 방법으로 데이터셋 등 정보 탈취, 평가 플랫폼의 공격 또는 오류 발생 시도 등의 행위를 한 경우" 가 포함되어 있기는 한데 NSML 시스템을 사용해서 데이터셋을 로컬로 다운받는 것이 비정상적인 방법으로 취급되는 지가 명확치 않아 문의드립니다.

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요.
데이터셋을 local로 다운로드하여 분석을 진행하는 것은 금지하고 있습니다.
감사합니다.
