### ISSUE TITLE
[NSML] 세션 에러

### ISSUE THREAD

**Issue by ZIZUN** [hunminjeongeum-korean-competition-2021/conversation-summary#17]
# 상황 (자세히 작성해주시면 좋습니다.)

팀: 화성갈끄니까
submit, run 둘다 세션 빌드되기전에 에러가 나네요. 해결 부탁드립니다.
자원이 부족하다는 경고메시지가 뜨기도 합니다.
도커 문제가 아닌거 같아요. nsml기본걸로 해도 같은 상황입니다.(제생각)

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

![image](https://user-images.githubusercontent.com/24732802/136749206-daa090f8-8691-44d0-aada-128fc8a278a2.png)
![image](https://user-images.githubusercontent.com/24732802/136747262-36f1ac1a-cac4-4332-acbb-b0dee3f42662.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@ZIZUN 님 조치되었습니다. #27 관련 이슈였습니다.

**Comment by ZIZUN** [comment]
@bluebrush 님 방금 다시 run 해봤는데 여전히 같은 상태입니다.
현재 해결된 것이 맞나요?
도커는 #nsml: dacon/nia-tf:1.0  기본 베이스라인 도커입니다.

nsml run -e main.py -d dialogue -g 1
![image](https://user-images.githubusercontent.com/24732802/136937419-7e77657f-9fa4-4b3e-82b1-49ed71417467.png)
