### ISSUE TITLE
[NSML] 운영측에서 답변이 없어 다른분들께 질문드립니다.. 혹시 NSML 접근에 사전조치가 필요하셨나요?

### ISSUE THREAD

**Issue by Usurper47** [hunminjeongeum-korean-competition-2021/conversation-summary#19]
# 주제
- NSML 로그인 불가

# 상황 (자세히 작성해주시면 좋습니다.)
- pdf를 읽어가면서 진행하려는데, NSML 로그인 자체가 안됩니다. (웹 및 터미널)
- 다른분들은 바로 로그인이 가능하셨나요 아니면 뭔가 거쳐가야하는 과정이 있는건가요?
- (제가 깃허브를 잘 다루지 못해서, 기초적인 것을 빼먹은게 아닐까도 싶습니다.)

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 권한도 받은 것 같은데.. 이게 아닌가요?
![image](https://user-images.githubusercontent.com/46472729/136753151-afa70562-ee10-480a-b366-8335a6ce8cb6.png)

# 기타 문의 사항
- 살려주세요.. 데이터라도 보고 싶습니다..

**Comment by ZIZUN** [comment]
왜그럴까요 ㅠ 저는 그냥 바로 됐어요..

**Comment by KHY13** [comment]
저같은경우에는 NSML 로그인은 됐는데 세션 생성할때 권한오류(?)같은게 발생해서 운영진측에서 해결해 주셨었어요

**Comment by Usurper47** [comment]
모두 감사드립니다! 내일 출근하실 때까지 기다려봐야겠네요!

**Comment by cosmoquester** [comment]
저도 github ID/PW로 하니까 로그인은 바로 됐어요! 주최측에 제공한 github 아이디로 등록해주신 것 같던데 문의를 해보시는 게 좋을 것 같아요

**Comment by devsungmin** [comment]
안녕하세요.

늦게 확인 해서 죄송합니다.

현재 저희 측에서 확인 해본 결과 `https://github.com/usurper47` 정보로 NSML측에 전달한 상태입니다.

따라서 NSML 계정 정보가 소문자로 입력되어 들어간것으로 확인됩니다.

해당 문제는 NSML측에 `Usurper47`로 다시 전달하도록 하겠습니다.

다시 한번 대회 진행에 어려움을 드려서 죄송합니다.
감사합니다.

**Comment by bluebrush** [comment]
@Usurper47 님, 반영되었습니다.
