### ISSUE TITLE
[NSML] 세션생성 오류

### ISSUE THREAD

**Issue by KHY13** [hunminjeongeum-korean-competition-2021/conversation-summary#2]
# 주제
-  NSML 세션생성 오류

# 상황 (자세히 작성해주시면 좋습니다.)
-  "nsml run -e main.py -d dialouge" 실행시 세션 생성 오류가 발생

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
-  안녕하세요 "nsml run -e main.py -d dialouge" 로 baseline 코드 실행시에 다음과 같은 오류가 발생합니다.
- 아직 오픈이 안된 것인지 계정등록이 안된 것인지 확인부탁드립니다.
![image](https://user-images.githubusercontent.com/55617916/136649165-4d8a505d-0818-4fad-9bd0-fb10ca84c74d.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@KHY13 님, 조치되었습니다. 다시 시도부탁드립니다 :)

**Comment by KHY13** [comment]
해결되었습니다. 감사합니다!
