### ISSUE TITLE
[NSML] 맞춤법 검사기 질문

### ISSUE THREAD

**Issue by ziggy321** [hunminjeongeum-korean-competition-2021/conversation-summary#21]
# 주제
- 맞춤법 검사기 질문

# 상황 (자세히 작성해주시면 좋습니다.)
- 개회식 qna에서 다른분의 질문에 맞춤법 검사기는 pretrained model에 해당하므로 사용할 수 없다고 답변한 것을 보았습니다.
- 룰베이스 맞춤법 검사기는 어떤가요? 이것도 허용되지 않는 건가요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@dacon-murdoch 님, 답변 가능하실까요?

**Comment by dacon-murdoch** [comment]
안녕하세요.
주어진 train data를 활용해 만들어진 맞춤법 검사기는 활용할 수 있지만,
외부 데이터를 활용하여 만들어진 rule based 맞춤법 검사기는 활용하실 수 없습니다.
감사합니다.
