### ISSUE TITLE
[NSML] nsml 에러 메세지 : An error occurred while initializing user information

### ISSUE THREAD

**Issue by ziggy321** [hunminjeongeum-korean-competition-2021/conversation-summary#22]
# 주제
- nsml 에러 메세지 : An error occurred while initializing user information

# 상황 (자세히 작성해주시면 좋습니다.)
- 베이스라인 코드를 돌려보려는 중에 에러가 납니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 다음과 같은 에러 메세지가 나옵니다.
- Error: An error occurred while initializing user information. Please contact dev team
FATA[2021/10/11 23:44:19.841] Internal server error
- 다른 분들은 docker 어쩌구라도 나오는데, 저는 사용자 정보를 초기화하면서 에러가 났다는, 아무도 안 뜨는 메세지가 나옵니다.

<img width="570" alt="스크린샷 2021-10-11 오후 11 46 34" src="https://user-images.githubusercontent.com/46099642/136810342-1041e4b3-21e2-4847-a669-a723a9821d7b.png">
 

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@hongjehong 님, 
아래 2개 명령의 comman line포함한 전체 메시지를 붙여주시기 바랍니다. 
`nsml login`
`nsml whoami`

**Comment by ziggy321** [comment]
<img width="569" alt="스크린샷 2021-10-12 오전 12 56 28" src="https://user-images.githubusercontent.com/46099642/136820253-ec1d48b4-757f-418b-b841-973696162b22.png">

@bluebrush 말씀하신 메세지 첨부하였습니다.

**Comment by ziggy321** [comment]
<img width="570" alt="스크린샷 2021-10-12 오후 12 27 07" src="https://user-images.githubusercontent.com/46099642/136886290-05a6544c-0ba3-4ded-838f-cb787eb883d5.png">

@bluebrush 기존 메세지와 언급하신 메세지 모두 연속적으로 출력된 캡쳐 첨부하였습니다.

**Comment by ziggy321** [comment]
@bluebrush 확인했습니다. 감사합니다.
