### ISSUE TITLE
[Dataset] train_data print 문 사용 가능여부

### ISSUE THREAD

**Issue by jonhyuk0922** [hunminjeongeum-korean-competition-2021/conversation-summary#23]
# 주제
- 코드 상 프린트문으로 학습데이터 EDA 가능한가요

# 상황 (자세히 작성해주시면 좋습니다.)
- 데이터에 대해서 EDA를 진행해보고 싶습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 코드상 print문을 넣어서 data 특징을 찍어봐도 될까요? 혹 불가능하다면 AI HUB 에 있는 35만건을 통한 EDA는 가능할까요??? 개회식에서 데이터 품질에 대해 테스트 해달라는 내용도 있었는데  어떻게 데이터를 확인해야할지 잘 모르겠어서 여쭤봅니다!!

# 기타 문의 사항
- NSML 플랫폼에 대해 설명해주시는 자리나, 슬렉같은 채널을 만들어주실순 없으실까요?

**Comment by dacon-murdoch** [comment]
안녕하세요.
print 문을 사용하여 EDA를 해보셔도 좋습니다. / 또한 AI HUB에 있는 데이터를 활용하여 전체적인 form을 확인하셔도 무방합니다.
기타 문의 사항에 대해서는 내부적으로 말씀드려 보겠습니다.
감사합니다.
