### ISSUE TITLE
[NSML] session is already removed.

### ISSUE THREAD

**Issue by jonhyuk0922** [hunminjeongeum-korean-competition-2021/conversation-summary#26]
# 주제
- submit 시 session 에러

# 상황 (자세히 작성해주시면 좋습니다.)
- 학습한 checkpoint로 제출하려고 할때 session이 이미 삭제되었다고 에러가 뜹니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- dev 팀에 문의하라는 내용이 담겨있습니다.
![스크린샷 2021-10-12 오후 6 13 03](https://user-images.githubusercontent.com/76195885/136927665-949cf6cc-26f6-4f5e-b878-0ff23174326a.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@jonhyuk0922 님, 조치되었습니다. #27 이슈입니다.
