### ISSUE TITLE
[NSML] 깃헙, nsml 등록이 안된 팀원이 있습니다.

### ISSUE THREAD

**Issue by hyeinhyun** [hunminjeongeum-korean-competition-2021/conversation-summary#3]
# 주제
- 

# 상황 (자세히 작성해주시면 좋습니다.)
- 팀원 중 한명이 깃헙 초대 및 nsml 접근 권한이 안되었습니다.
- 팀 : 여우면, 팀원 : 임소영
- 깃헙 아이디 : sy2399 / 깃헙 이메일 : syrhim94@gmail.com  입니다. 확인부탁드립니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by devsungmin** [comment]
안녕하세요 @hyeinhyun 님

제출해주신 Github 계정을 확인해보니 임소영님 계정은 `soyoung`으로 확인됩니다.

감사합니다.

**Comment by sohyunwriter** [comment]
안녕하세요. @devsungmin 님
해당 팀원의 '닉네임'이 아니라 '이름'으로 깃헙 계정이 잘못 전달되었는데요.
깃헙 이메일은 동일합니다.

**기존 soyoung 계정 취소해주시고, sy2399로 재초대 부탁드립니다.**

감사합니다.

**Comment by devsungmin** [comment]
안녕하세요. @sohyunwriter, @hyeinhyun 님

늦게 답변 드려서 죄송합니다.

기존 제출해주신 계정 확인하여 NSML 측에 변경 요청 드렸습니다.

감사합니다.

**Comment by bluebrush** [comment]
@sohyunwriter @devsungmin 님, 요청사항 반영되었습니다. (10-10 14:10)

**Comment by hyeinhyun** [comment]
감사합니다!

**Comment by sohyunwriter** [comment]
@bluebrush 잘못 초대된 soyoung 계정 취소 부탁드립니다!
