### ISSUE TITLE
[Dataset] train dataset 에서 Life가 여가생활인가요? 주거와생활인가요? 

### ISSUE THREAD

**Issue by nlp-parkwonjae** [hunminjeongeum-korean-competition-2021/conversation-summary#30]
# 주제
- train dataset에서 Life의 정확한 의미

# 상황 (자세히 작성해주시면 좋습니다.)
- 학습용 데이터셋으로 5개의 파일을 사용하는데, Edu, Food, Life, Per_Rel, Work를 사용한다고 했습니다. 
- AIhub의 원본 데이터셋으로 유추해보아 Edu = 시사교육 / Food = 식음료 / Per_Rel = 개인및관계 / Work = 일과직업로 파악했는데 Life 파일은 여가생활인지 주거와생활인지 명확하게 알 수 없었습니다. 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 
![image](https://user-images.githubusercontent.com/85141914/136948172-8a5afbcb-2c72-4c02-a366-02b92c0d9ef4.png)

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요.
life는 주거와 생활입니다.
감사합니다.
