### ISSUE TITLE
[NSML] Rejected: not enough credit (balance: 0)

### ISSUE THREAD

**Issue by Usurper47** [hunminjeongeum-korean-competition-2021/conversation-summary#31]
# 주제
-  크래딧 할당이 안되어 있는 것 같습니다...

# 상황 (자세히 작성해주시면 좋습니다.)
- 세션 생성이 안됩니다.
- 아이디 관련하여, 다음과 같은 이슈를 겪었습니다.
    - https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization/issues/19
- 다음과 같은 과정을 거쳐 해결하려고자 시도했으나, (github verify 이슈) 이는 문제가 아닌 것 같습니다.
    - https://github.com/hunminjeongeum-korean-competition-2021/speaker-recognition/issues/13#issuecomment-940103684 
    -  https://github.com/ai-starthon/AI_Starthon2019/issues/23#issuecomment-513702711
- 다음과 같은 해결방법을 문의드리는 중이나, 세부적으로 살펴보니 Rejected 메세지가 다릅니다. 
    -  https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization/issues/27
    -  ![image](https://user-images.githubusercontent.com/46472729/137004953-4aae5108-6128-448e-a98a-7dbe9b7ff4f6.png)
- 결론: 아이디 관련하여 배정할 때, 크래딧을 주지 않으신 것 같습니다. 할당 부탁드립니다.
- 팀 아이디: nia2001

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
![image](https://user-images.githubusercontent.com/46472729/137003200-e477bceb-27aa-4cd8-bec8-c0f216592b3c.png)
![image](https://user-images.githubusercontent.com/46472729/137003554-10b44df8-7e5b-417a-9201-5e57013faa8b.png)

# 기타 문의 사항
- 아이디 이슈 3일, 크래딧 이슈 1일.. 개인사정상 수~금 작업이 어려운데, 적어도 토요일에는 실행이 가능했으면 좋겠습니다.. 
- 운영진분들 파이팅임미다..

**Comment by devsungmin** [comment]
해당 내용 NSML측에 전달 하도록 하겠습니다.

감사합니다.

**Comment by bluebrush** [comment]
@Usurper47 님, credit 설정되었습니다. 계정 재설정 과정에서 credit 누락되었습니다.
