### ISSUE TITLE
Tokenzier도 Pretrained 된 것을 사용하면 안되나요?

### ISSUE THREAD

**Issue by SeungyounShin** [hunminjeongeum-korean-competition-2021/conversation-summary#32]
예를 들어 HuggingFace 같은 곳에서 가져와도되나요?

_Originally posted by @dan-legit in https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization/issues/1#issuecomment-939252666_

**Comment by taerangi** [comment]
안녕하세요. 
본 대회에서는 pre-trained된 tokenizer도 사용 불가합니다.
감사합니다.

**Comment by SeungyounShin** [comment]
mecab 은 써도되는데 hugging face 는 안되는것인가요?

**Comment by vetaerang** [comment]
@SeungyounShin 답변 정정드립니다.
pre-trained tokenizer 사용 가능합니다. (기존에 사용 불가하다고 답변 드렸었습니다.)
hugging face에서 tokenizer 가져와서 사용 가능합니다.
추가로, hugging face에서 모델을 가져와서 사용할 경우 weight를 초기화한 상태로 사용해주셔야 합니다. (모델은 pre-trained 사용불가)
혼동 드려 죄송합니다.

**Comment by hyeinhyun** [comment]
@taerangi 안녕하세요, 한번더 확인을 위해 여쭤봅니다.
토크나이저의 경우 개인적으로 수집, 가지고 있는데이터로 학습된 토크나이저를 hugging face에 올려서 사용할 수 있다는말이 맞나요?
