### ISSUE TITLE
[NSML] NSML Session에 대한 질문

### ISSUE THREAD

**Issue by SeungyounShin** [hunminjeongeum-korean-competition-2021/conversation-summary#33]
내부적으로 LM 같이 훈련시킨후 요약에 대해 fine-tunning 한다면 
LM 을 훈련시켜 Session 이 종료된 후에도 다른 Session 에서 불러올 수 있나요?

**Comment by nammyoungjin** [comment]
https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/load_model.html
여기 내용 확인해보시면 될것같아요
