### ISSUE TITLE
[NSML] Permission denied 데이터 셋 접근 권한을 주시지 않았습니다.

### ISSUE THREAD

**Issue by Usurper47** [hunminjeongeum-korean-competition-2021/conversation-summary#34]
# 주제
- 데이터 셋 접근 권한을 설정해주세요.

# 상황 (자세히 작성해주시면 좋습니다.)
- 직전 이슈입니다.
- https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization/issues/31
    - 대소문자로 인한 nsml 접근 불가 -> 재설정 -> 크레딧 미설정 -> 크레딧 부여 -> 데이터 셋 접근 권한 미설정

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 오타인가 싶어서 여러가지 처봤는데 아닙니다.
![image](https://user-images.githubusercontent.com/46472729/137065580-2a47ba93-2dfc-420c-97db-3defc050af66.png)
- 데이터 셋 접근 권한이 없습니다
![image](https://user-images.githubusercontent.com/46472729/137065627-7afe1f36-bb9d-4df6-b813-3f73b865976b.png)
- Resources 창의 출력도 변한 것 같습니다만, 제가 진단할 수 있는 문제가 아닙니다.
![image](https://user-images.githubusercontent.com/46472729/137065760-ca4002e2-c236-4be2-9d80-b6d086991840.png)
- 새로고침에 따라 p40 이 생겼다가 없어집니다.
![image](https://user-images.githubusercontent.com/46472729/137065838-05d4b3c5-96cc-4c11-96e9-5ef5bed69d98.png)

# 기타 문의 사항
- 이번에는 같은 이슈가 없도록 다른 참가자분의 권한/설정과 비교/대조 부탁드립니다

**Comment by bluebrush** [comment]
@Usurper47 님, 제가 확인해보니, private 설정 변경되어 있는 부분이 확인되어 다시 public으로 변경하였습니다. 
이력에 대해서는 관련되신분들께 문의중입니다. 
참고로 그림에 첨부하신 리소스는 공용 자원입니다. 현재 대회는 모두 전용자원을 사용하므로 그림의 리소스 영역은 사용하지 않고 있습니다. 
10-13 13:24
