### ISSUE TITLE
[Dataset] 토크나이저 생성 관련

### ISSUE THREAD

**Issue by KHY13** [hunminjeongeum-korean-competition-2021/conversation-summary#36]
# 주제
- 토크나이저  생성 관련

# 상황 (자세히 작성해주시면 좋습니다.)
- 토크나이저를 만들때 NSML상에 있는 학습데이터만을 사용해야 하나요? Aihub에서 다운 가능한 학습데이터로 생성해도 괜찮은지 궁금합니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by vetaerang** [comment]
@KHY13 안녕하세요.
토크나이저를 만들 때도 NSML에 업로드되어있는 학습데이터만 사용해주셔야 합니다.
감사합니다.

**Comment by KHY13** [comment]
@taerangi 넵 감사합니다.
