### ISSUE TITLE
[NSML] 다른 팀분들께 여쭤봅니다. 10월 13일 18시 기준 정상적으로 작업 가능하신가요?

### ISSUE THREAD

**Issue by Usurper47** [hunminjeongeum-korean-competition-2021/conversation-summary#37]
# 주제
- 현재 정상적으로 작업 중인 팀의 수가 궁금합니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 대회 5일차
- 20팀 중 10팀이 제출했고, 2회 이상 제출한 팀이 3팀으로 매우 적습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 현황을 알아야 제쪽에서 해결할 수 있는 문제인지 파악할 수 있을 것 같습니다.
- 이게 다들 안되는건지 저만 안되는건지 알고싶습니다. ㅠㅠ
- 답글로 알려주세요! 부탁드립니다!

# 기타 문의 사항
-

**Comment by onestep00** [comment]
저는 수정 없는 코드로 됐다가 안됐다가 합니다.

**Comment by kabbi159** [comment]
저희 팀은 16시 51분까지 안되는 것 확인하고, 18시 12분에 Session 시작 성공하였습니다.

**Comment by ZIZUN** [comment]
저는 지금 정상적으로 돼요

**Comment by Usurper47** [comment]
와 저는 19시 이전까지 안되다가 지금 되네요. 설정 변경은 없었습니다.

**Comment by ZIZUN** [comment]
다들 화이링
