### ISSUE TITLE
[NSML] Inference 방식 (동작 과정)

### ISSUE THREAD

**Issue by KyungHyunLim** [hunminjeongeum-korean-competition-2021/conversation-summary#38]
# 주제
-  Inference 방식 (동작 과정)

# 상황 (자세히 작성해주시면 좋습니다.)
- nsml submit session_name checkpoint_num 으로 제출을 하게 되는데, 이때 inference가 어떤식으로 동작을 하는지 궁금합니다.
- 저희가 두개의 다른 세션에서 각각 tokenizer와 model을 불러와야하는데 이 과정을 어떻게 적용해야할 지 몰라서 문의합니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- submit 하는 checkpoint를 생성했던 main 함수에서 if args.mode == 'train' : 이전 까지 실행이 되고, bind 되어있는 inference 함수가 실행이 되는 걸까요?
- 아니면, submit 하는 checkpoint를 생성했던 .py 파일에 정의 되어 있는 inference 함수만 따로 실행되는 것 일까요?

# 기타 문의 사항
-

**Comment by vetaerang** [comment]
@KyungHyunLim 안녕하세요.
`nsml submit`을 실행하면, 다음 절차에 따라 진행됩니다.
1. main.py 실행 (`if args.mode == 'train' :` 이전까지 실행되며, 이 때 `bind_model()`이 실행되어야 합니다.)
2. `bind_model()` 후 `nsml.paused()` 실행
3. `bind_model()`에서 정의한 `load()` 함수 실행
4. `bind_model()`에서 정의한 `infer()` 함수 실행
(매개변수로 test 데이터셋의 경로를 받게 되며, 리턴 값은 **[(확률, 요약생성문)]** 형태여야 합니다. 
확률값은 score에 영향을 미치지 않으니 아무 값이나 넣어주셔도 됩니다.)
5. `infer()`로 반환한 요약생성문에 대해 평가 산식 적용 후 리더보드 업데이트

감사합니다.
