### ISSUE TITLE
[NSML] 메캅 토크나이저 사용 관련 문의

### ISSUE THREAD

**Issue by hyeinhyun** [hunminjeongeum-korean-competition-2021/conversation-summary#39]
# 주제
- 

# 상황 (자세히 작성해주시면 좋습니다.)
- 안녕하세요 #9 에서 여쭤본 메캅토크나이저 사용 여부 및 사용 방법에 대해 설명 부탁드립니다. 
( 저희 요약 팀은 커스텀 도커를 사용할 수가 없어 메캅사용을 위한 외부데이터를 nsml에 올릴 수 없는것으로 알고있습니다. )

감사합니다.
# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by vetaerang** [comment]
@hyeinhyun 안녕하세요.
Custom Docker 사용 가능합니다.
konlpy [공식문서](https://konlpy.org/ko/latest/install/#ubuntu) 참고하셔서 도커 이미지 빌딩 후,
setup.py 상단에 `#nsml: custom_docker_repo_name`  형식으로 써주시면 해당 도커 이미지 환경으로 실행됩니다.
`nsml run` 실행시 setup.py는 main.py와 같은 경로에 있어야 합니다.
감사합니다.

**Comment by hyeinhyun** [comment]
넵 감사합니다:)

**Comment by devsungmin** [comment]
안녕하세요 @hyeinhyun님

Docker와 관련된 글은 [NSML Docker Custom Image 만드는 방법](https://github.com/hunminjeongeum-korean-competition-2021/docs/blob/main/DockerImage.md)을 참고 부탁드립니다.

감사합니다 :)
