### ISSUE TITLE
[NSML] 세션실행 오류

### ISSUE THREAD

**Issue by P4RK-J4EWOONG** [hunminjeongeum-korean-competition-2021/conversation-summary#4]
# 주제
- NSML 세션 실행 오류

# 상황 (자세히 작성해주시면 좋습니다.)
- baseline 코드가 "nsml run -e main.py -d dialogue"로 실행이 되질 않습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 처음에는 baseline 코드가 위의 커맨드로 정상적으로 작동했는데, 지금은 완전히 새롭게 baseline 코드를 git clone해서 실행해도 아래와 같은 에러가 발생합니다.
- ![스크린샷 2021-10-09 오후 10 57 31](https://user-images.githubusercontent.com/58019542/136660826-f832af4c-7485-411f-9334-84df6bd2132c.png)

# 기타 문의 사항
-

**Comment by P4RK-J4EWOONG** [comment]
시간이 지나니까 알아서 정상적으로 작동하는 것 같아요 :)

그런데 저희가 잘못해서 이런 문제가 발생하는 건지, 아니면 순간적으로 플랫폼이 불안정해서 그런건지는 잘 모르겠어요.

도중에는 아래와 같은 오류가 발생했었습니다.

<img width="1275" alt="스크린샷 2021-10-10 오전 1 24 55" src="https://user-images.githubusercontent.com/58019542/136666497-ac8e311c-be55-4faf-8a34-1f724b1805f5.png">

**Comment by MattYoon** [comment]
저도 아까는 잘됐는데, 1시간 동안 이 에러만 반복하네요. 서버가 많이 불안정한거 같아요.

**Comment by cosmoquester** [comment]
저도 저런 에러들이 계속 나오면서 계속 실행하다보면 가끔씩(?) 정상 동작하네요

**Comment by bluebrush** [comment]
@P4RK-J4EWOONG 님, 첫 화면의 이슈는 조치되었습니다. #27 이슈였습니다.
