### ISSUE TITLE
[NSML] 답변이 없어서 다시 문의 드립니다.

### ISSUE THREAD

**Issue by ziggy321** [hunminjeongeum-korean-competition-2021/conversation-summary#40]
# 주제
- Error: An error occurred while initializing user information. Please contact dev team

# 상황 (자세히 작성해주시면 좋습니다.)
- 캡쳐와 같은 에러가 발생합니다. 말씀 주신 대로 nsml login, nsml whoami, nsml run 모두 캡쳐한 사진을 올렸습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 
<img width="570" alt="136886290-05a6544c-0ba3-4ded-838f-cb787eb883d5" src="https://user-images.githubusercontent.com/46099642/137266619-86d1a433-9ec4-4232-b91f-82e050db05a1.png">

# 기타 문의 사항
- 아래와 같은 이메일이 날아오긴 합니다. 근데 저 인증 코드를 입력할 방법도 없네요. 
- Device verification code 요구를 비활성화하는 방법도 찾아보니 없는데, 왜 저만 이런 문제가 발생하는지도 잘 모르겠습니다.
-
<img width="1188" alt="스크린샷 2021-10-14 오후 4 01 00" src="https://user-images.githubusercontent.com/46099642/137267561-0e3e55fc-54bb-4e39-b17c-c1458daa6815.png">

**Comment by bluebrush** [comment]
@hongjehong 님, 확인이 늦었습니다. 조치되었습니다.

**Comment by ziggy321** [comment]
@bluebrush 확인했습니다. 감사합니다.
