### ISSUE TITLE
[NSML] inference 결과 제출 포맷

### ISSUE THREAD

**Issue by onestep00** [hunminjeongeum-korean-competition-2021/conversation-summary#41]
# 주제
- infer() 함수의 제출 포맷

# 상황 (자세히 작성해주시면 좋습니다.)
- infer() 결과 포맷

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- [dialogue-summarization README.md](https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization#readme) 의 설명은 다음과 같고
> `id`와 `summary` column을 모두 기입한 DataFrame을 결과물로 구성(최종 제출 format)
***
- https://github.com/hunminjeongeum-korean-competition-2021/dialogue-summarization/issues/38#issuecomment-942972337 이 답변은 다음과 같습니다.
> (매개변수로 test 데이터셋의 경로를 받게 되며, 리턴 값은 **[(확률, 요약생성문)]** 형태여야 합니다. 
***
- 둘중에 어떤 방식이어야 하는지, 혹은 **요약생성문** 이 `["id", "summary"]` 인건지 정확히 어떤 포맷으로 `return` 하면 되나 궁금합니다.
- 감사합니다.

# 기타 문의 사항
-

**Comment by vetaerang** [comment]
@onestep00 안녕하세요.

리턴 값은 [(확률, 요약생성문)] 형태여야합니다.
ex) [(0, '철수는 점심을 먹었다.'), (0, '짱구는 학원에 갔다.') ... ] 

위의 포맷에서 요약생성문만 가져와서 채점하도록 되어있습니다.
확률 값은 점수에 영향이 없으므로 아무 값이나 넣어주셔도 무관합니다.

감사합니다.
