### ISSUE TITLE
[Dataset] 사용가능 컬럼 문의 

### ISSUE THREAD

**Issue by Usurper47** [hunminjeongeum-korean-competition-2021/conversation-summary#42]
# 주제
- data에 들어있는 모든 정보 ( type, topic, gender, residentialProvince)를 학습과 추론에도 사용 가능한가요?

# 상황 (자세히 작성해주시면 좋습니다.)
- train 및 test 데이터에 존재하는 몇몇 컬럼은, 대화 이외의 추가적인 주제를 포함합니다.
- 대화 전반의 상황을 반영하는 주제나 유형이 있습니다.
- 단순 대화 텍스트로는 알 수 없는 정보인 성별과 지역 등의 부가적인 정보가 있습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 이들을 모델의 학습과 추론에 사용해도 될까요?
- 기타 컬럼에 대한 허용 여부도 자세히 알고 싶습니다.

# 기타 문의 사항
- 토크나이저 허용으로 변경된 이슈를 공지해주실 수 있을까요?

**Comment by vetaerang** [comment]
@Usurper47 안녕하세요.
data에 들어있는 모든 정보 ( type, topic, gender, residentialProvince)는 학습과 추론에 사용 가능합니다.
토크나이저 관련 내용은 오늘 중으로 정리하여 공지 올릴 예정입니다.
감사합니다.
