### ISSUE TITLE
[NSML] gpu가 계속 사용중이라고 뜹니다!

### ISSUE THREAD

**Issue by KyungHyunLim** [hunminjeongeum-korean-competition-2021/conversation-summary#43]
# 주제
- gpu가 계속 사용중이라고 뜹니다!  
- The GPU limit was exceeded (max: 1, usage: 1, requested: 1)

# 상황 (자세히 작성해주시면 좋습니다.)
- 제가 test로 제출을 해보려다 명령어에 -t를 붙이는 것을 깜빡하고, 명령어를 실행 후 crtl+z로 바로 중지 시켜버려습니다. 그런데 gpu가 반환 되지 않고 계속 The GPU limit was exceeded (max: 1, usage: 1, requested: 1) 오류가 떠 test를 진행하지 못하고 있습니다!

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by KyungHyunLim** [comment]
해결하였습니다!

**Comment by dan-legit** [comment]
혹시 어떻게 해결하셨나요? 저도 계속 할당중이라고 나와서요!

**Comment by dan-legit** [comment]
nsml rm 으로 삭제되는군요ㅎㅎ

**Comment by KyungHyunLim** [comment]
넵!
nsml ps 로 돌아가고 있는 세션확인하고
nsml rm으로 삭제해주었습니다!
