### ISSUE TITLE
[NSML] 공개된 사전학습 모델 허용 해주시면 안될까요?

### ISSUE THREAD

**Issue by ZIZUN** [hunminjeongeum-korean-competition-2021/conversation-summary#44]
# 주제
- 공개된 사전학습 모델 허용 해주시면 안될까요?

# 상황 (자세히 작성해주시면 좋습니다.)
- 훈련셋은 데이터가 너무너무 적고 이것만으로는 생성모델 학습이 솔직히 불가능한 것 같은데요..
- rouge L 계산식에 맞게, 학습데이터의 요약문을 통계적으로 분석해서
- "싶다며 있는지 이에 대해 해야 한다는 거라고 안 될 것 같다고 하자고 좋겠고 있었다고 이야기를 얘기를 하고 한다. 있다."
- 값을 test 결과값으로 넣으니 10.9로 오히려 좋게 나오는 것 같아요..
- 사전학습 없이 생성 테스크를 하기는 어렵다고 생각합니다. 허용해주셔서 더 재밌는 대회가 되었으면 좋겠습니다 ㅠ

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by Cho-Geonwoo** [comment]
위에 말씀해주신 바와 같이 답을 fix하여 제출하는 것은 답안 수기 작성이라는 규칙에 위배되지 않나요? @bluebrush

**Comment by vetaerang** [comment]
@ZIZUN 안녕하세요. 
규정상 사전학습 모델을 사용하는 것은 불가합니다. 다만, 사전학습된 Tokenizer는 사용 가능합니다.
감사합니다.

**Comment by vetaerang** [comment]
@Cho-Geonwoo 학습된 모델의 추론 결과로 나온 값이 아닌, 수기로 정답값을 입력하는 경우 답안 수기 작성에 해당하여 실격처리됩니다.

**Comment by ZIZUN** [comment]
@taerangi 어.. 그럼 혹시 제 스코어 초기화 가능하실까요?? 전 바로 실격인가요?

**Comment by Usurper47** [comment]
통계적 분석도 일종의 모델로 볼 수 있을 것 같습니다. 
가령 LDA로 특정 토픽을 뽑아서 토픽 내부의 워드를 출력값으로 넣는 것은 문제가 되지 않는 것처럼요.
모델 학습이 잘 안돼서 1위분 솔루션이 굉장히 궁금했는데, 손해가 될 수 있음에도 이렇게 이슈화 해주셔서 감사합니다.

**Comment by ZIZUN** [comment]
@Usurper47 ㅎㅎ 아녜요. 꼭 1등하시길 바랍니다!!

**Comment by vetaerang** [comment]
@ZIZUN 당장 실격 처리되지는 않고, 
예선 종료 후 참가자들의 최종제출물 코드 검증 과정에서 cheating 요소가 있을 경우 실격 처리할 예정입니다.
리더보드에 올라갈 최종 제출물에서 cheating 요소가 없도록 신경써주시면 됩니다.

**Comment by ZIZUN** [comment]
@taerangi 오오.. 기회를 주셔서 감사합니다 ㅎㅎ 귀찮게 해드려 죄송해요! 최선을 다해봐야겠어요.
