### ISSUE TITLE
[NSML] ROUGE 평가 코드 제공이 가능할까요?

### ISSUE THREAD

**Issue by KyungHyunLim** [hunminjeongeum-korean-competition-2021/conversation-summary#49]
# 주제
- ROUGE 평가 코드 제공이 가능할까요?

# 상황 (자세히 작성해주시면 좋습니다.)
- ROUGE 평가 코드 제공이 가능할까요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- ROUGE 평가 코드 제공이 가능할까요? gpu가 1대 밖에 없는 상황에서 최적의 모델을 선택하기 위해서 평가코드가 제공되면 좋을것 같습니다.

# 기타 문의 사항
-

**Comment by vetaerang** [comment]
평가 코드는 제공이 어렵습니다. 도움 드리지 못해 죄송합니다.
