### ISSUE TITLE
[NSML] 리더보드 초기화 후 submit이 안 됩니다

### ISSUE THREAD

**Issue by sohyunwriter** [hunminjeongeum-korean-competition-2021/conversation-summary#50]
# 주제
- 리더보드 초기화 후 submit이 안 됩니다.

# 상황 (자세히 작성해주시면 좋습니다.)
![image](https://user-images.githubusercontent.com/44013936/137892504-8ce3526c-0812-44e4-bfe3-831ec9f9bb6a.png)

-submit 할 때 /data/dialogue/evaluation.py 코드에 문제가 있다고 뜹니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 리더보드 초기화 과정에서 evaluation 코드에 오류가 있는 것 같습니다.
- 해당 코드는 저희쪽에서 볼 수가 없는데 수정 부탁드립니다.
- 또, evaluation 코드 공유해주실 수 있을까요?

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@taerangi 님, 확인부탁드립니다.

**Comment by Usurper47** [comment]
베이스라인 새로 받아서 진행했는데 동일했습니다.
![image](https://user-images.githubusercontent.com/46472729/137893804-6da8b724-2a5d-4d15-9e7a-1abef19056a0.png)

**Comment by vetaerang** [comment]
@Usurper47 @sohyunwriter 해당 문제 조치중입니다. 잠시만 기다려주세요! 죄송합니다.

**Comment by hyeinhyun** [comment]
@taerangi 안녕하세요, 제출을 진행했는데 0.00 점이 나옵니다. 제출한 팀이 다 이점수가 나온것같네요. 
함께 확인부탁드립니다 :)

**Comment by vetaerang** [comment]
@hyeinhyun @Usurper47 @sohyunwriter 해당 문제 조치되었습니다. 다시 제출 시도해주시기 바랍니다.

**Comment by vetaerang** [comment]
evaluation 파일은 공개가 어렵습니다. 죄송합니다.
