### ISSUE TITLE
[NSML] 파일 시스템 사용

### ISSUE THREAD

**Issue by dan-rtzr** [hunminjeongeum-korean-competition-2021/conversation-summary#51]
# 주제
- nsml 파일 시스템 사용

# 상황 (자세히 작성해주시면 좋습니다.)
- 현재 pretrained 모델 학습, fine-tuning 학습을 나눠서 진행하려고 하는데요. 이 때 tokenizer 파일, pretrained 모델의 checkpoint 등을 저장해야 합니다. 여러 개의 파일을 서로 다른 상황에서 저장하고 불러와야 하는데 nsml.bind/save/load의 주어진 예제만으로는 어떻게 사용해야 할 지 모르겠습니다.
- 예를 들면 main 함수 초반에는 tokenizer 파일을 저장해야 하고, 후반에는 모델의 체크포인트들을 저장해야 합니다. 또한 저는 현재 hugging face의 trainer를 사용하여 학습을 진행하고 있는데, 이 경우 자동으로 로컬 파일시스템에 checkpoint가 저장되는데 nsml.save를 어떻게 사용해야 할 지 잘 모르겠습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)

**Comment by onestep00** [comment]
저는 pytorch lightning을 이용하고 있는데, 커스텀 콜백을 만들어 모델을 저장하고있습니다. 콜백에서 nsml.save 를 직접 호출하는식으로 사용중입니다.

**Comment by dan-rtzr** [comment]
@onestep00 
감사합니다.
그렇다면 모델 저장하는 함수 외에 다른 것을 저장하는 메쏘드를 만들어서 두개를 사용할 수는 없겠죠? save에 한 개의 함수만 바인딩 시켜야 하니까요?

**Comment by onestep00** [comment]
nsml.save 에 바인드시키거나 save_fn 에 지정한 함수 안에서 모델, 토크나이저등 한번에 저장하시면 될것같습니다.
시점이 달라서 여러 함수를 nsml.save 에 바인드시키고싶으시면 저장 시점에 명시적으로 nsml.save(save_fn=함수) 로 지정해서 사용하면 여러 함수를 동적으로 nsml.save에 연결할 수 있었습니다.

**Comment by ZIZUN** [comment]
비인딩 함수를 여러개 만들어서(ex 토크나이저용, 모델용) 바인딩하고 save or load하고 다른함수로 바인딩하고 save or load할수있습니다. 저는 그런식으로 하는중입니다

**Comment by dan-rtzr** [comment]
@ZIZUN 감사합니다. 그럼 궁금한게 있는데요, 아래와 같이 두개의 바인딩 함수를 만든다고 했을때 각각의 save와 load를 어떻게 사용해야 할까요? 이렇게 접근하는게 맞는건가요?

```
def bind_model(model):
    def save(dir_name):

    def load(dir_name):

    nsml.bind(save=save, load=load)


def bind_tokenizer(tokenizer):
    def save(file_name):
        
    def load(dir_name):

    nsml.bind(save=save, load=load)
```

**Comment by onestep00** [comment]
호출하기전에 매번 바인딩 함수를 호출하면 되긴 합니다.
### 예시
```
# 모델 저장시
bind_model(model)
nsml.save("checkpoint")
# 토크나이저 저장시
bind_tokenizer(tokenizer)
nsml.save("checkpoint")
```
저는 그래서 bind 하는 대신 `nsml.save("checkpoint", save_fn=save)` 이런식으로 nsml.save 호출할때 그냥 함수를 같이 넣어서 호출했습니다.
`nsml.save(load)` 호출 시 우선순위가 1. save(load)_fn 2. bind 3. 내부 디폴트 로 작동한다고 해서요.

**Comment by dan-rtzr** [comment]
계속 답변 달아주셔서 감사합니다! 저도 save_fn을 사용하려는데요, 2가지 의문점이 있습니다. 아래와 같은 함수를 만들어서 사용한다고 할 때,
1. dir_name 파라미터는 어떻게 save_fn에 전달하는가?
2. tokenizer나 model 같은 object는 어떻게 save_fn 안에서 사용해야 하는가? (아래 예시 같은 경우는 tokenizer 객체는 위에서 global하게 선언되긴 했지만 이렇게 사용하는게 맞는지 모르겠습니다.)

일단 이렇게 사용하는게 아닌거 같습니다. 실행해보니 에러가 나네요. 혹시 도움 주실 수 있다면 감사하겠습니다. 혹은 예시 코드로 주셔도 좋을 거 같습니다!

```
def save_tokenizer(dir_name):
   os.makedirs(dir_name, exist_ok=True)
   save_dir = os.path.join(dir_name, "tokenizer.json")
   tokenizer.save(save_dir)

nsml.save("checkpoint", save_fn=save_tokenizer)
```

**Comment by onestep00** [comment]
1. `nsml.save` 의 첫번째 인자가 전달되는 것 같습니다.
2. 저는 아래 예시처럼 wrapper 함수를 만들어서 미리 전달했습니다.

```
def nsml_save(filepath, trainer, save_weights_only):
    def inner_save(filepath):
        return trainer.save_checkpoint(os.path.join(filepath, "checkpoint.ckpt"), save_weights_only)

    return inner_save

class NsmlModelCheckpoint(ModelCheckpoint):
    def _save_nsml(self, trainer: "pl.Trainer", filepath):
        filepath = Path(str(filepath)).stem
        nsml.save(
            filepath, save_fn=nsml_save(filepath=filepath, trainer=trainer, save_weights_only=self.save_weights_only)
        )
    def _save_last_checkpoint(self, trainer: "pl.Trainer", monitor_candidates: Dict[str, _METRIC]) -> None:
        if not self.save_last:
            return
        self._save_nsml(trainer, self.CHECKPOINT_NAME_LAST)
```

제 코드는 이렇습니다.
함수 `nsml_save`에 필요한 변수들을 넘겨놓고 `nsml_save`에서 준 변수를 받은 `inner_save`가 `save_fn`에 전달됩니다.
`filepath`는 `nsml.save`에서 넘겨주게 됩니다.
저장할 때 다른 변수들을 사용하기 때문에 wrapper 를 만든 것 말고는 같은 구조인 것 같은데 어떤 오류가 나시나요?

**Comment by dan-rtzr** [comment]
@onestep00 @ZIZUN @taerangi @bluebrush
어제 답변 주셔서 체크포인트에 모델과 토크나이저가 저장이 잘 되었습니다. 감사합니다.
문제는 프리트레인 모델 학습을 완료한 뒤 fine-tuning을 위해 새로운 세션을 열어서 새로운 학습 코드를 실행하려고 합니다. 그래서 완료된 세션에서 모델을 불러오려고 하는데요, 문제는 그 세션에 저장된 체크포인트 로드가 안되서 도움을 구합니다.

```
def load_model(dir_name):
    os.listdir(dir_name)
    global model
    model = BartForConditionalGeneration.from_pretrained(dir_name)

load_model_checkpoint= "64"
nsml.bind(load=load_model)
nsml.load(load_model_checkpoint, load_fn=load_model(load_model_checkpoint), session="nia2021/dialogue/154")
```

이렇게 세션을 정하고 체크포인트를 정해서(ex. 64) 로드를 하려고 하는데, 경로를 못찾더라고요. 그래서 os.listdir을 하니 현재 세션의 python 코드 파일만 존재하고 해당 세션에서 저장된 체크포인트 경로는 보이지 않더라고요. 다른 세션에 저장된 프리트레인 모델을 로드해서 fine tuning 하려는데 혹시 아신다면 방법을 알려주시면 감사하겠습니다!

 참고로 아래와 같이 세션에 체크포인트와 모델 등의 필요한 데이터는 저장되어 있습니다.
![image](https://user-images.githubusercontent.com/89378766/138323386-cb7630d5-fcb3-4bf1-a84e-3f74e60e2fb1.png)
![image](https://user-images.githubusercontent.com/89378766/138323458-0b0542da-4173-48c5-805d-ea8a6fc67dba.png)

**Comment by onestep00** [comment]
load_fn에 함수를 전달할 때 함수의 return이 아닌 함수 자체를 전달해야 할 것 같습니다.

**Comment by dan-rtzr** [comment]
@onestep00 감사합니다. 잘 되네요! 이슈 close 하겠습니다.
