### ISSUE TITLE
[NSML] nsml submit 관련

### ISSUE THREAD

**Issue by dan-rtzr** [hunminjeongeum-korean-competition-2021/conversation-summary#53]
@taerangi

# 주제
- nsml submit 시 docker container 가동이 안됩니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 모델 학습은 모두 완료되고 해당 세션 내에 load, infer에 대해서 bind를 모두 시켜두었습니다. 그리고 nsml submit으로 제출하려는데 해당 세션의 컨테이너가 없다고 나옵니다. 혹시 아시는 분 있으면 도움 부탁드립니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
**nsml submit 로그**
```
❯ nsml submit -t nia2021/dialogue/183 1
.......
Building docker image. It may take a while
.......nia2021/dialogue/184: Session ready
nia2021/dialogue/184: Load model
load nsml model takes 0.06128883361816406 seconds

Session nia2021/dialogue/184 is started
.Infer test set. The inference should be completed within 3600 seconds.
.Traceback (most recent call last):
TypeError: 'NoneType' object is not subscriptable

Infer test set takes 0.21599960327148438 seconds
.Done
You can see session log using [nsml logs nia2021/dialogue/184]
```
**nsml 세션 로그**
![image](https://user-images.githubusercontent.com/89378766/138388805-3c691574-25e1-4184-9b10-b0a2c6bd7e17.png)

# 기타 문의 사항
-

**Comment by dan-rtzr** [comment]
계속 도와주셨는데, 실례겠지만 그래도 도움을 구하고자 태그해보겠습니다.
@onestep00 @ZIZUN

**Comment by bluebrush** [comment]
@dan-rtzr 님, 
submit 규격이 GPU 1, CPU 7장 인데요. 
nia2021/dialogue/183 이 GPU 0으로 학습하신 세션으로 확인됩니다. GPU 1장을 포함해서 학습하셔야 submit이 가능할 것으로 보입니다. -g 0으로 학습하지 않으시면 될 것 같습니다.

**Comment by ZIZUN** [comment]
@dan-rtzr 님 이럴 경우에는, -g 1 설정으로 다른 세션에있는 finetune된 모델을 가져와서 새로운 세션에 다시 저장하시고 inference하시면 될거같아요.

**Comment by dan-rtzr** [comment]
말씀해주신대로 잘 해결했습니다. 이슈 close 하겠습니다.
