### ISSUE TITLE
[Dataset] inference를 위한 리턴 형태 문의드립니다

### ISSUE THREAD

**Issue by hyeinhyun** [hunminjeongeum-korean-competition-2021/conversation-summary#6]
# 주제
-  inference를 위한 리턴 형태 문의드립니다

# 상황 (자세히 작성해주시면 좋습니다.)
- 안녕하세요, 코드를 보다가 리턴결과가 리턴 결과는 [(확률, 0 or 1)] 의 형태라고하는데, 여기서 '확률'의 의미가 무엇인지 설명부탁드립니다.
- 또한, 0 or 1 binary로 리턴되는게 맞나요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- <img width="669" alt="스크린샷 2021-10-09 오후 11 22 35" src="https://user-images.githubusercontent.com/41287040/136661970-f40e0ace-8aef-4488-bb56-f1dcb1f68897.png">

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요.
해당 주석은 무시하신 후
docs의 데이터 설명을 참고하시어 요약문을 작성해주시면 됩니다.

**Comment by nammyoungjin** [comment]
<img width="766" alt="스크린샷 2021-10-14 오후 5 37 38" src="https://user-images.githubusercontent.com/33752068/137281977-81199a30-58ff-4347-960b-60730bf3fd2f.png">

위의 데이터 포맷에 맞춰 

est_result = pd.DataFrame( {'id': test_dialogue_id, 'summary': test_summary})
return test_result


다음과 같이 코드를 작성하였습니다. 하지만 추론시 다음과 같은 에러가 발생했습니다.

<img width="750" alt="스크린샷 2021-10-14 오후 5 38 27" src="https://user-images.githubusercontent.com/33752068/137282122-62bd1b78-47f4-4c09-a9b4-27b2b93765ad.png">

혹시 정확한 추론 제출 포맷을 알 수 있을까요?
