### ISSUE TITLE
[NSML] NSML에 로그인이 되질 않습니다.

### ISSUE THREAD

**Issue by Usurper47** [hunminjeongeum-korean-competition-2021/conversation-summary#7]
# 주제
- 

# 상황 (자세히 작성해주시면 좋습니다.)
- 현 계정으로 NSML에 접근하고자 하면, 다음과 같은 출력이 나옵니다.
> You are not a registered user. Please contact the administrator. ( dl_nsml_alpha@navercorp.com )

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 팀명: 3줄 요약
- 성명: 서일 (1인 팀)
- 대표 이메일: joil47@ajou.ac.kr
- 대표 github 프로필 링크: https://github.com/usurper47
- 대표 github 프로필 닉네임: Usurper47
- 참여자 정보의 메일 주소: joil47@ajou.ac.kr
> 메일용 계정과 git 용 계정이 따로 있습니다. 또 닉네임의 대소문자 차이가 있습니다.
- 아니면 제가 뭔가 놓친게 있을까요? 

# 기타 문의 사항
-

**Comment by Usurper47** [comment]
이틀 동안 데이터조차 확인할 수 없었는데, 오늘도 해결이 안되는 걸까요?

**Comment by bluebrush** [comment]
@Usurper47 님, 변경 등록되었습니다.
