### ISSUE TITLE
[NSML] GPU부족

### ISSUE THREAD

**Issue by ZIZUN** [hunminjeongeum-korean-competition-2021/conversation-summary#8]
# 주제
- 

# 상황 (자세히 작성해주시면 좋습니다.)
- 아무래도 자원이 부족한 것 같은데 해결 부탁드립니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
 제가 문제인 건지 모르겠지만 GPU가 부족한 것 같아요.
![image](https://user-images.githubusercontent.com/24732802/136664645-d6ae18bf-4b38-4028-9fde-d2b79e346b87.png)

# 기타 문의 사항
- 고생하세요 감사합니다.

**Comment by bluebrush** [comment]
@ZIZUN 님, 위 자원뷰는 공용 pool에 대한 내용입니다 
현재 각 팀은 별도 설정된 전용 pool을 사용하고 있습니다. 
자원 현황은
`nsml status -r` , `nsml status -r -v` 로 확인 가능합니다.

**Comment by ZIZUN** [comment]
아하 그렇군요! 이제 잘돼요 감사합니다.
